[colors-dark]
blur=yes
# Match theme terminal transparency behavior.
alpha = 0.45
alpha-mode = all

foreground = CBCED0
background = 1c1e26

cursor = 1C1E26 E3E6EE

regular0 = 1c1e26
regular1 = e95678
regular2 = 29d398
regular3 = FAC29A
regular4 = 26bbd9
regular5 = ee64ac
regular6 = 59E1E3
regular7 = CBCED0

bright0 = 6F6F70
bright1 = ec6a88
bright2 = 3fdaa4
bright3 = fbc3a7
bright4 = 3fc4de
bright5 = f075b5
bright6 = 6be4e6
bright7 = E3E6EE
