#      dMMMMMP dMP dMP dMMMMMP dMMMMb dMMMMMMP            
#     dMP     dMP dMP dMP     dMP dMP   dMP               
#    dMMMP   dMP dMP dMMMP   dMP dMP   dMP                
#   dMP      YMvAP" dMP     dMP dMP   dMP                 
#  dMMMMMP    VP"  dMMMMMP dMP dMP   dMP                  
#                                                         
#      dMP dMP .aMMMb  dMMMMb  dMP dMMMMMP .aMMMb  dMMMMb 
#     dMP dMP dMP"dMP dMP.dMP amr   .dMP" dMP"dMP dMP dMP 
#    dMMMMMP dMP dMP dMMMMK" dMP  .dMP"  dMP dMP dMP dMP  
#   dMP dMP dMP.aMP dMP"AMF dMP .dMP"   dMP.aMP dMP dMP   
#  dMP dMP  VMMMP" dMP dMP dMP dMMMMMP  VMMMP" dMP dMP    
#                                                         



background            #1C1E26
foreground            #CBCED0

background_opacity 0.45

# black
background_blur 1
color0  #1C1E26
color8  #6F6F70

# red
color1  #E95678
color9  #EC6A88

# green
color2  #29D398
color10 #3FDAA4

# yellow
color3  #FAC29A
color11 #FBC3A7

# blue
color4  #26BBD9
color12 #3FC4DE

# magenta
color5  #EE64AC
color13 #F075B5

#cyan
color6  #59E1E3
color14 #6BE4E6

# white
color7  #CBCED0
color15 #E3E6EE

#  
#  _______/\\\\\_______/\\\\\\____________/\\\__                                                  
#   _____/\\\///\\\____\////\\\___________\/\\\__                                                 
#    ___/\\\/__\///\\\_____\/\\\___________\/\\\__                                                
#     __/\\\______\//\\\____\/\\\___________\/\\\__                                               
#      _\/\\\_______\/\\\____\/\\\______/\\\\\\\\\__                                              
#       _\//\\\______/\\\_____\/\\\_____/\\\////\\\__                                             
#        __\///\\\__/\\\_______\/\\\____\/\\\__\/\\\__                                            
#         ____\///\\\\\/______/\\\\\\\\\_\//\\\\\\\/\\_                                           
#          ______\/////_______\/////////___\///////\//__                                          
#  ______/\\\\\\\\\\\________________/\\\_______________________/\\\______________________        
#   _____\/////\\\///________________\/\\\______________________\/\\\______________________       
#    _________\/\\\___________________\/\\\______________________\/\\\______________________      
#     _________\/\\\_________/\\\\\____\/\\\____________/\\\\\____\/\\\____________/\\\\\____     
#      _________\/\\\_______/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__\/\\\\\\\\\____/\\\///\\\__    
#       _________\/\\\______/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_\/\\\////\\\__/\\\__\//\\\_   
#        __/\\\___\/\\\_____\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__\/\\\__\/\\\_\//\\\__/\\\__  
#         _\//\\\\\\\\\_______\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___\/\\\\\\\\\___\///\\\\\/___ 
#          __\/////////__________\/////_____\/////////______\/////_____\/////////______\/////_____
#  
